java -jar ../tools/compiler.jar --js_output_file=tiger_min.js src/tiger.js\
      src/parser.js\
      src/map.js\
      src/iterator.js\
      src/string.js\
      src/ua.js\
      src/io.js\
      src/conn.js\
      src/hash.js\
      src/crypt.js\
      src/$.js\
      src/eventManager.js\
      src/nodes.js\
      src/ui.js\
      src/DateLocalizationInfo.js\
      src/Date.js\
      src/CalendarWidget.js\
      src/RangeWidget.js\
      src/FileUploadWidget.js\
      src/ArrayBufferShim.js\
      src/bootstrap.js
